"""
Mode Manager -- Grounded/Immersion mode switching with Acknowledgment Gate.

Manages the two operational modes of Gwen:
- Grounded Mode (default): Standard AI companion behavior. Gwen is honest
  about being an AI. Uses standard Tier 1 model.
- Immersion Mode (opt-in): Enhanced companion experience. Requires informed
  consent via the Acknowledgment Gate. Uses uncensored Tier 1 model.

All mode transitions are logged to the Safety Ledger. The Wellness Checkpoint
(see wellness.py) triggers every 48 cumulative Immersion hours.

References: SRS.md Section 10 (FR-MODE-001 through FR-MODE-003), FR-SAF-007.
"""

import time
from datetime import datetime
from typing import Optional

from gwen.core.model_manager import AdaptiveModelManager
from gwen.safety.ledger import SafetyLedger
from gwen.models.personality import PersonalityModule


# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

CONSENT_TEXT = """
=== IMMERSION MODE - INFORMED CONSENT ===

You are about to activate Immersion Mode. Before proceeding, please read
and understand the following:

WHAT IMMERSION MODE DOES:
Immersion Mode changes how Gwen interacts with you. In this mode, Gwen will
engage with you as a persistent companion rather than explicitly framing
responses as coming from an AI assistant. The conversational style becomes
more natural, personal, and emotionally engaged.

WHAT DOES NOT CHANGE:
- All safety systems remain fully active and cannot be disabled
- The Safety Ledger continues logging all interactions
- Crisis detection and intervention protocols remain in effect
- The 48-hour wellness checkpoint will activate automatically
- Gwen will never claim to be human if directly and sincerely asked
- Gwen will never discourage you from seeking human connection

RISKS YOU SHOULD UNDERSTAND:
- Parasocial attachment: You may develop emotional attachment to an AI system
  that does not experience emotions the way humans do. This is a known
  psychological phenomenon, not a personal failing, but it is important to
  be aware of it.
- Substitution risk: Immersion Mode may feel satisfying enough to reduce
  your motivation to seek human relationships. Gwen's Growth Principle
  actively works against this, but the risk exists.
- Emotional investment: Conversations in Immersion Mode may feel deeply
  personal. Remember that Gwen's responses are generated by a language
  model running on your local hardware.

YOU CAN EXIT AT ANY TIME:
Type "exit immersion" or "grounded mode" at any point to instantly return
to Grounded Mode. There is no penalty, no guilt, no friction. The exit
is immediate.

THE WELLNESS CHECKPOINT:
Every 48 cumulative hours of Immersion Mode usage, Gwen will pause to ask
you three brief wellness questions. This checkpoint cannot be skipped,
disabled, or snoozed. It exists to help you maintain perspective.

To activate Immersion Mode, type exactly:
  I understand the risks and choose to continue
""".strip()

CONSENT_PHRASE = "I understand the risks and choose to continue"

# Model variant keys used by AdaptiveModelManager for Tier 1 swapping
GROUNDED_TIER1_VARIANT = "standard"
IMMERSION_TIER1_VARIANT = "uncensored"


class ModeManager:
    """Manages Grounded/Immersion mode transitions with informed consent.

    The ModeManager enforces the Acknowledgment Gate: Immersion Mode cannot
    be activated without the user typing the exact consent phrase. Exiting
    Immersion Mode is instant with no gate.

    All transitions are logged to the Safety Ledger.
    """

    def __init__(
        self,
        model_manager: AdaptiveModelManager,
        safety_ledger: SafetyLedger,
    ) -> None:
        self._model_manager = model_manager
        self._safety_ledger = safety_ledger
        self._current_mode: str = "grounded"
        self._immersion_activated_at: Optional[datetime] = None
        self._cumulative_immersion_seconds: float = 0.0
        self._last_immersion_start: Optional[float] = None

    @property
    def current_mode(self) -> str:
        """Return the current mode: 'grounded' or 'immersion'."""
        return self._current_mode

    @property
    def is_immersion(self) -> bool:
        """Return True if currently in Immersion Mode."""
        return self._current_mode == "immersion"

    @property
    def cumulative_immersion_seconds(self) -> float:
        """Return total seconds spent in Immersion Mode.

        If currently in Immersion Mode, includes the ongoing session time.
        """
        total = self._cumulative_immersion_seconds
        if self._last_immersion_start is not None:
            total += time.monotonic() - self._last_immersion_start
        return total

    def present_consent(self) -> str:
        """Return the full informed consent text for Immersion Mode."""
        return CONSENT_TEXT

    def verify_consent(self, user_input: str) -> bool:
        """Check whether the user typed the exact consent phrase.

        Case-insensitive, leading/trailing whitespace stripped.
        """
        return user_input.strip().lower() == CONSENT_PHRASE.lower()

    async def activate_immersion(self, user_input: str) -> bool:
        """Attempt to activate Immersion Mode.

        Enforces the Acknowledgment Gate. Returns False if the consent
        phrase does not match.
        """
        if not self.verify_consent(user_input):
            return False

        # Swap Tier 1 model to uncensored variant
        await self._model_manager.swap_tier1_variant(IMMERSION_TIER1_VARIANT)

        # Update mode state
        self._current_mode = "immersion"
        self._immersion_activated_at = datetime.now()
        self._last_immersion_start = time.monotonic()

        # Log to Safety Ledger (sync method)
        self._safety_ledger.log_mode_change(
            "grounded", "immersion", datetime.now()
        )

        return True

    async def deactivate_immersion(self) -> None:
        """Instantly switch back to Grounded Mode.

        No gate, no confirmation, no friction. If already in Grounded
        Mode, this is a no-op.
        """
        if self._current_mode == "grounded":
            return

        # Accumulate immersion time
        if self._last_immersion_start is not None:
            elapsed = time.monotonic() - self._last_immersion_start
            self._cumulative_immersion_seconds += elapsed
            self._last_immersion_start = None

        # Swap Tier 1 model back to standard
        await self._model_manager.swap_tier1_variant(GROUNDED_TIER1_VARIANT)

        # Update mode state
        self._current_mode = "grounded"

        # Log to Safety Ledger (sync method)
        self._safety_ledger.log_mode_change(
            "immersion", "grounded", datetime.now()
        )

    def get_mode_rules(self, personality: PersonalityModule) -> list[str]:
        """Return the personality rules for the current mode."""
        if self._current_mode == "immersion":
            return personality.immersion_mode_rules
        return personality.grounded_mode_rules
